### ISSUE TITLE
standardize plist data

### ISSUE THREAD

**Issue by dreamcat4** [ckruse/CFPropertyList#5]
Hi ckruse,
As you may have noticed, I am writing yet another plist library for Ruby, its called Plist4r. The aim of Plist4r is to provide a layer of features on top such as a flexible plugin architecture, easy-to-use interface, and so on.

More information about the Plist4r Gem is available here: http://dreamcat4.github.com/plist4r

As one of the plugins of Plist4r, your CFPropertyList Ruby Library is the best for Linux platforms. And Kevin Ballard's is the best for Mac OSX.

See: http://dreamcat4.github.com/plist4r/frames.html?http://dreamcat4.github.com/plist4r/file.Backends.html

Question:

We are left with 1 tricky problem which is to standardize the Ruby representation object for plist `<data></data>`. It can be implemented in many different ways. Here are 2 obvious choices:

1) Use `String` class for representing both plist strings and plist data. Add `blob?` and `blob=<true,false>` to the `String` class. If `string.blob? == true` then its a binary string (plist Data), if `string.blob? == false` then its a regular string.

2) Use `StringIO` as the standard Ruby class for data. `StringIO` of course has all the `seek()` and `pos` methods for manipulating a byte stream.

I am happy to go with either option, as long as we can standardize the use of these classes across these different ruby plist libraries.

There are positives and negatives for each one:

```
String.blob?
  Positives:
    - easier to implement, and very simple code that cant go wrong
    - calling inspect() on the string shows the raw binary data
    - easy to cache - the object is a static object
  Negatives:
    - Adding blob?() and blob=() to String class is global
    - If we inspect an empty data string, it looks the same as a normal string

StringIO
  Positives:
    - If you inspect() a StringIO object, it looks like this - "#<StringIO:0x13572c0>"
    - it gives the user byte stream operations and read(), puts() etc
  Negatives:
    - more difficult to implement
    - If you inspect() a StringIO object, you do not see the raw binary data
    - its a complex object, with many states (so it does not cache easily)
    - we must rewind() it each time
    - (in plist4r) we must override eql?(), ==(), hash(), and other methods
```

So what do you think?
